name: Pre-commit check

on:
  pull_request:
    branches: [master]
  workflow_run:
    workflows: ["Build Container"]
    types: [completed]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image.outputs.name }}
    steps:
      - name: Set image name to lowercase
        id: image
        run: echo "name=$(echo 'ghcr.io/${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  pre-commit:
    needs: prepare
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success'
    container:
      image: ${{ needs.prepare.outputs.image_name }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Initialize git (for pre-commit)
        run: git init && git config user.email "ci@example.com" && git config user.name "CI"
      - name: Run pre-commit
        run: pre-commit run --all-files
