name: Pre-commit check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository | downcase }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository | downcase }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run pre-commit
        run: pre-commit run --all-files
