name: Test Report

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_LOWER: ${{ github.repository | tolower }}
    container:
      image: ghcr.io/${{ env.IMAGE_NAME_LOWER }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      PYTHONPATH: /app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests and generate JSON report
        run: |
          pytest --json-report --json-report-file=report.json > coverage_report.txt 2>&1 || true
          cat coverage_report.txt
      - name: Post test report to PR
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GITHUB_API_URL: ${{ github.api_url }}
        run: python .github/scripts/post_test_report.py
