name: Test Report

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [master]
  workflow_run:
    workflows: ["Build Container"]
    types: [completed]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image.outputs.name }}
    steps:
      - name: Set image name to lowercase
        id: image
        run: echo "name=$(echo 'ghcr.io/${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  test:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.prepare.outputs.image_name }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      PYTHONPATH: /app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests and generate JSON report
        run: |
          pytest --json-report --json-report-file=report.json > coverage_report.txt 2>&1 || true
          cat coverage_report.txt
      - name: Post test report to PR
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GITHUB_API_URL: ${{ github.api_url }}
        run: python .github/scripts/post_test_report.py
